;Custom_OpenClash_Rules
;全分组防 DNS 泄漏订阅转换模板
;作者：https://github.com/Aethersailor
;项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules
;基于 ACL4SSR 模板魔改而来，感谢原作者！
;<必须>搭配本项目配套教程，实现最佳化的 OpenClash 使用效果！
;教程：https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88
;有问题可提 issue，或者加入本项目 Telegram 群组进行讨论
;Telegram 群组：https://t.me/custom_openclash_rules_group
;Telegram 通知频道：https://t.me/custom_openclash_rules

[custom]
;设置规则标志位
;以下规则，按照从上往下的顺序遍历，优先命中上位规则
;修改顺序会影响分流效果
ruleset=🏚️ VPN,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/VPN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/nas_direct.list,28800
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/zdy_direct.list,28800
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list,28800
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list,28800
ruleset=☁️ 自定代理,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/zdy_proxy.list,28800
ruleset=🚀 节点选择,https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list,28800
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list,28800
ruleset=🎯 全球直连,[]GEOSITE,google-cn
ruleset=🚀 节点选择,https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list,28800
ruleset=🎯 全球直连,[]GEOSITE,steam@cn
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list,28800
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=📲 Telegram,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list,28800
ruleset=🕊️ Twitter(X),[]GEOSITE,twitter
ruleset=🕊️ Twitter(X),[]GEOIP,twitter,no-resolve
ruleset=💬 ChatGPT,[]GEOSITE,openai
ruleset=💬 Copilot,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list,28800
ruleset=🤖 AI服务,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list,28800
ruleset=🤖 AI服务,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list,28800
ruleset=🚀 GitHub,[]GEOSITE,github
ruleset=🚀 测速工具,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list,28800
ruleset=📹 YouTube,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list,28800
ruleset=🎥 AppleTV+,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.list,28800
ruleset=🍎 苹果服务,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list,28800
ruleset=Ⓜ️ 微软服务,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list,28800
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi.list,28800
ruleset=📢 谷歌FCM,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list,28800
ruleset=🇬 谷歌服务,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list,28800
ruleset=🎶 TikTok,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list,28800
ruleset=🎥 Netflix,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list,28800
ruleset=🎥 DisneyPlus,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list,28800
ruleset=🎥 HBO,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list,28800
ruleset=🎥 HBO,https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/HBO_fix.list,28800
ruleset=🎥 PrimeVideo,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list,28800
ruleset=🎥 Emby,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list,28800
ruleset=🎥 Emby,https://gh-proxy.com/https://raw.githubusercontent.com/ddgksf2013/Filter/refs/heads/master/Emby.list,28800
ruleset=🎻 Spotify,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list,28800
ruleset=📺 Bahamut,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list,28800
ruleset=🎶 网易音乐,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list,28800
ruleset=📺 国内媒体,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list,28800
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/IPTVMainland_Domain.list,28800
ruleset=🌎 国外媒体,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list,28800
ruleset=🛒 国外电商,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list,28800
ruleset=🛒 国外电商,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonIP/AmazonIP.list,28800
ruleset=🛒 国外电商,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Shopee/Shopee.list,28800
ruleset=🛒 国外电商,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopify/Shopify.list,28800
ruleset=🛒 国外电商,https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Ozon.list,28800
ruleset=🎮 游戏平台,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list,28800
ruleset=🎮 游戏平台,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list,28800
ruleset=🎮 游戏平台,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list,28800
ruleset=🎮 游戏平台,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list,28800
ruleset=🎮 游戏平台,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list,28800
ruleset=🎮 游戏平台,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list,28800
ruleset=🎮 Steam,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list,28800
ruleset=🚀 节点选择,[]GEOSITE,gfw
ruleset=🎯 全球直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list,28800
;京东青龙面板直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/zdy_finaldirect.list
ruleset=🎯 全球直连,[]GEOSITE,cn
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
;节点地区分组参考本项目推荐机场而设立

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🏚️ VPN`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=☁️ 自定代理`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🚀 GitHub`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📲 Telegram`select`[]♻️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🕊️ Twitter(X)`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=💬 ChatGPT`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=💬 Copilot`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🤖 AI服务`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🎶 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🎥 DisneyPlus`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🎥 HBO`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🎥 PrimeVideo`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🎥 AppleTV+`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🎥 Emby`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🎻 Spotify`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📺 Bahamut`select`[]🚀 节点选择`[]🎯 全球直连
custom_proxy_group=🎶 网易音乐`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=📺 国内媒体`select`[]🎯 全球直连
custom_proxy_group=🌎 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🛒 国外电商`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连
custom_proxy_group=🇬 谷歌服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🎮 Steam`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🚀 测速工具`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT

;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
