[custom]
;大陆白名单模式，无污染，无泄漏，降低延迟提升响应速度！

;设置规则标志位
ruleset=📢 谷歌服务,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=⛔️ 不走代理,[]DOMAIN-SUFFIX,time.windows.com
ruleset=⛔️ 不走代理,[]DOMAIN-SUFFIX,client.wns.windows.com
;PT下载IP直连
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/nas_direct.list,28800
;自定义直连规则
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/zdy_direct.list,28800
ruleset=☁️ 自定代理,https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/zdy_proxy.list,28800
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🤖 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🤖 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
;青龙IP直连
ruleset=⛔️ 不走代理,clash-classic:https://raw.githubusercontent.com/ooojoker/Clash_rule/refs/heads/main/rules/zdy_finaldirect.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=📢 谷歌服务,[]DOMAIN-KEYWORD,google
ruleset=⛔️ 不走代理,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list,28800
ruleset=🐟 漏网之鱼,[]FINAL

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]⛔️ 不走代理`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=☁️ 自定代理`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=📢 谷歌服务`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=💬 Ai平台`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]♻️ 自动选择`[]⛔️ 不走代理`
custom_proxy_group=🇺🇸 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🚨 应急分组`url-test`[]🇿🇦 南非 失联`[]🇺🇸 美国 失联01`[]🇺🇸 美国 失联02`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⛔️ 不走代理`select`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
